baseurl = "/"
title = "Joahn-lab"
copyright = "Copyright &copy; 2019 - Joahn"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = "joahn-lab"
    gitlab = ""
    linkedin = ""
    facebook = ""
    instagram = "babyblu_deepdown"

[params]
    tagline = "All we want is around us"
    
    # options for highlight.js (version, additional languages, and theme)
    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/joahn-lab"
[[menu.main]]
    name = "Instagram"
    url = "https://instagram.com/babyblu_deepdown"